apiVersion: apps/v1
kind: Deployment
metadata:
  name: udapeople-test
  labels:
    app: udapeople
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-udapeople
   template:
    metadata:
      labels:
        app: blue-udapeople
    spec:
      containers:
      - name: blue-frontend
        image: docker.io/ankit4all/capstoneprojudacity:frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: blue-udapeople-frontend
spec:
  selector:
    app: udapeople
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
