apiVersion: apps/v1
kind: Deployment
metadata:
  name: udapeople
  labels:
    app: udapeople
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udapeople
  template:
    metadata:
      labels:
        app: udapeople
    spec:
      containers:
      - name: frontend
        image: docker.io/ankit4all/capstoneprojudacity:frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: udapeople-frontend
spec:
  selector:
    app: udapeople
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 6000
  type: LoadBalancer
