apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: upplCluster
    region: ap-south-1
    version: "1.21"

availabilityZones: ["ap-south-1a", "ap-south-1b", "ap-south-1c"]

managedNodeGroups:
  - name: upplNodeGroup
    desiredCapacity: 3
    instanceType: t2.micro
    volumeSize: 8
