apiVersion: apps/v1
kind: Deployment
metadata:
  name: udapeople-prod
  labels:
    app: udapeople-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udapeople-prod
  template:
    metadata:
      labels:
        app: udapeople-prod
    spec:
      containers:
      - name: green-frontend
        image: docker.io/ankit4all/capstoneprojudacity:frontend
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: green-udapeople-frontend
spec:
  selector:
    app: udapeople-prod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
