version: 2.1

jobs:
    build:
        docker: 
            - image: cimg/python3.8
        steps:
            - checkout
            - restore_cache:
                keys: build-dependencies
            - run:
                name: Install Dependencies
                command: |
                    python3 -m venv venv
                    . venv
            